-- ============================================================================
-- QUERY 1: The Colorado Wealth Group, LLC - Firm Information
-- CRD Number: 310024
-- ============================================================================
-- This query retrieves all firm information from ria_firms_current
-- ============================================================================

SELECT 
    CRD_ID,
    ID,
    NAME,
    PHONE,
    FINTRX_URL,
    TEAM_PAGE,
    AI_BIO,
    ENTITY_CLASSIFICATION,
    TYPE_ENTITY,
    
    -- AUM Information
    DISCRETIONARY_AUM,
    NON_DISCRETIONARY_AUM,
    TOTAL_AUM,
    AVERAGE_ACCOUNT_SIZE,
    AUM_YOY,
    AUM_3YOY,
    AUM_5YOY,
    
    -- Account Information
    TOTAL_DISCRETIONARY_ACCOUNTS,
    TOTAL_NON_DISCRETIONARY_ACCOUNTS,
    TOTAL_ACCOUNTS,
    
    -- Client Base Information
    CLIENT_BASE,
    NUM_OF_CLIENTS_HIGH_NET_WORTH_INDIVIDUALS,
    NUM_OF_CLIENTS_NON_HIGH_NET_WORTH_INDIVIDUALS,
    NUM_OF_CLIENTS_BANKING_OR_THRIFT_INSTITUTIONS,
    NUM_OF_CLIENTS_INVESTMENTCOMPANIES,
    NUM_OF_CLIENTS_BUSINESS_DEVELOPMENT_COMPANIES,
    NUM_OF_CLIENTS_POOLED_INVESTMENT_VEHICLES,
    NUM_OF_CLIENTS_PENSION_AND_PROFIT_SHARING_PLANS,
    NUM_OF_CLIENTS_CHARITABLE_ORGANIZATIONS,
    NUM_OF_CLIENTS_STATE_OR_MUNICIPAL_GOVERNMENT_ENTITIES,
    NUM_OF_CLIENTS_INSURANCE_COMPANIES,
    NUM_OF_CLIENTS_OTHER_INVESTMENT_ADVISERS,
    NUM_OF_CLIENTS_SOVEREIGN_WEALTH_FUNDS_FOREIGN_OFFICIAL_INSTS,
    NUM_OF_CLIENTS_CORPS_OR_OTHER_BUSINESSES_NOT_LISTED_ABOVE,
    NUM_OF_CLIENTS_OTHER,
    
    -- AUM by Client Type
    AMT_OF_AUM_HIGH_NET_WORTH_INDIVIDUALS,
    AMT_OF_AUM_NON_HIGH_NET_WORTH_INDIVIDUALS,
    AMT_OF_AUM_BANKING_OR_THRIFT_INSTITUTIONS,
    AMT_OF_AUM_INVESTMENT_COMPANIES,
    AMT_OF_AUM_BUSINESS_DEVELOPMENT_COMPANIES,
    AMT_OF_AUM_POOLED_INVESTMENT_VEHICLES,
    AMT_OF_AUM_PENSION_AND_PROFIT_SHARING_PLANS,
    AMT_OF_AUM_CHARITABLE_ORGANIZATIONS,
    AMT_OF_AUM_STATE_OR_MUNICIPAL_GOVERNMENT_ENTITIES,
    AMT_OF_AUM_INSURANCE_COMPANIES,
    AMT_OF_AUM_SOVEREIGN_WEALTH_FUNDS_AND_FOREIGN_OFFICIAL_INSTS,
    AMT_OF_AUM_CORPORATIONS_OR_OTHER_BUSINESSES_NOT_LISTED_ABOVE,
    AMT_OF_AUM_OTHER_INVESTMENT_ADVISERS,
    AMT_OF_AUM_OTHER,
    
    -- Location Information
    MAIN_OFFICE_ADDRESS_1,
    MAIN_OFFICE_ADDRESS_2,
    MAIN_OFFICE_CITY_NAME,
    MAIN_OFFICE_STATE,
    MAIN_OFFICE_COUNTRY_NAME,
    ZIP_CODE,
    COUNTY,
    ADDITIONAL_OFFICES,
    
    -- Business Information
    BUSINESS_ACTIVITIES,
    ADVISORY_ACTIVITIES,
    FEE_STRUCTURE,
    INVESTMENTS_UTILIZED,
    ALTERNATIVES,
    TAMP_AND_TECH_USED,
    
    -- Employee Information
    NUM_OF_EMPLOYEES,
    EMPLOYEE_PERFORM_INVESTMENT_ADVISORY_FUNCTIONS_AND_RESEARCH,
    EMPLOYEE_REGISTERED_AS_A_BROKER_DEALER,
    LICENSED_AGENTS_OF_AN_INSURANCE_COMPANY,
    
    -- Investment Style
    CAPITAL_ALLOCATOR,
    PROGRESSIVE_INVESTMENT_STYLE,
    ACTIVE_ESG_INVESTOR,
    IS_AN_ADVISER_TO_ANY_PRIVATE_FUND,
    
    -- Asset Allocation (SMA Holdings)
    EXCHANGE_TRADED_EQUITY_SECURITIES,
    NON_EXCHANGE_TRADED_EQUITY_SECURITIES,
    U_S_GOVERNMENT_AGENCY_BONDS,
    U_S_STATE_AND_LOCAL_BONDS,
    SOVEREIGN_BONDS,
    INVESTMENT_GRADE_CORPORATE_BONDS,
    NON_INVESTMENT_GRADE_CORPORATE_BONDS,
    DERIVATIVES,
    SECS_ISSUED_BY_REGISTERED_INVEST_COMPS_BIZ_DEVMENT_COMPS,
    SECS_ISSUED_POOLED_INVST_VCLS_REG_INVST_COMPS_BIZ_DVMNT_COMPS,
    CASH_AND_CASH_EQUIVALENTS,
    
    -- Custodian Information
    CUSTODIAN_PRIMARY_BUSINESS_NAME,
    
    -- Additional Information
    ALLOCATOR_INTEL,
    ACCOLADES,
    ACTIVE,
    SEC_STATUS_EFFECTIVE_DATE,
    LATEST_UPDATE

FROM `savvy-gtm-analytics.FinTrx_data_CA.ria_firms_current`
WHERE CRD_ID = 310024

